### ISSUE TITLE
Lare2d compile error: gm1 has no implicit type

### ISSUE THREAD

**Issue by arussellMHD** [Warwick-Plasma/Lare2d#2]
Compiling the Lare2d (with gfortran on a Mac) returned error message:
```
src/core/conduct.f90:103:18: 
         temp = gm1 * rho(ix,iy) / (kappa1 * temp**pow)
Error: Symbol 'gm1' at (1) has no IMPLICIT type
```

Comparing to Lare3d, it looks like the consistent fix is to change line 103 of src/core/conduct.f90 to 
         `temp = rho(ix,iy) / (2.0_num * kappa1 * temp**pow)`
(After which the code compiles with no errors.)

Please can I check I'm not unwittingly breaking something?

**Comment by TomGoffrey** [comment]
Fixed by d34a0cf4ffb5ba2298b685d4d4f22cb53389da25
